services:
#  automated-timeline:
#    ports:
#      - 8034:8080

  database:
    image: 'postgres:15.2'
    ports:
      - '5431:5432'
    environment:
      - 'POSTGRES_USER=admin'
      - 'POSTGRES_DB=auto-db'
      - 'POSTGRES_PASSWORD=password'